# Generated by Django 4.1 on 2022-08-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='total_cost',
        ),
    ]
