# Generated by Django 4.1 on 2022-08-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('free_place', models.PositiveIntegerField()),
                ('stars', models.PositiveIntegerField(default=0, max_length=5)),
            ],
        ),
    ]
