# Generated by Django 4.1 on 2022-08-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='stars',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
