# Generated by Django 4.1 on 2022-08-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotels_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
