# Generated by Django 4.1 on 2022-08-16 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='like',
        ),
    ]
