# Generated by Django 4.1 on 2022-08-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_remove_favorite_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='like',
            field=models.BooleanField(default=False, verbose_name='favorite'),
        ),
    ]
